apiVersion: v1
kind: ReplicationController
metadata:
  name: gfw-app-server
  namespace: demo
spec:
  replicas: 1
  selector:
    app: gfw-app-server
  template:
    metadata:
      labels:
        app: gfw-app-server
    spec:
      containers:
        - name: gfw-app-server-container
          image: 192.168.1.45:5000/gfw/app:latest
          ports:
          - containerPort: 1081
---
apiVersion: v1
kind: Service
metadata:
 name: gfw-app-service
 namespace: demo
spec:
   ports:
   - name: gfw-app-out-in
     port: 21081
     targetPort: 1081
   externalIPs: [192.168.1.47]
   selector:
     app: gfw-app-server
